[package]
name = "pythonc"
version = "0.0.0"
description = "An example Python compiler (that can only compile a small subset of Python)"
edition = "2021"
publish = false

[dependencies]
xrcf = { path = "../xrcf/" }
anyhow = "1.0.86"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
indoc = "2"
